apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-js-app
  labels:
    app: next-js-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-js-app
  template:
    metadata:
      labels:
        app: next-js-app
    spec:
      containers:
      - name: next-js-app
        image: daraye/dpa:v1
        ports:
        - containerPort: 8080
