name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'helm/**'

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Configure npm retries (reduce 429s)
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000

      - name: Install deps (CI)
        run: |
          npm ci --no-audit --no-fund || npm i --no-audit --no-fund

      - name: Build
        env:
          CI: true
        run: npm run build

      - name: Test (only if script exists)
        env:
          NODE_ENV: test
          CI: true
        run: |
          # Runs tests if "test" script exists. Otherwise skip gracefully.
          npm run -s test --if-present || echo "No test script found; skipping tests."

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (CI)
        run: |
          npm ci --no-audit --no-fund || npm i --no-audit --no-fund

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  docker_push:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/next-js-app:${{ github.run_id }}
            ${{ secrets.DOCKERHUB_USERNAME }}/next-js-app:latest

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: docker_push
    steps:
      - name: Checkout (with token)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "'${{ github.run_id }}'"/' helm/js-app-chart/values.yaml

      - name: Commit and push changes
        run: |
            git config --global user.email "karaam130@gmail.com"
            git config --global user.name "daraye-tech"
            git add helm/js-app-chart/values.yaml
            git commit -m "Update tag in Helm chart"
            git push
