name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'helm/**'   # won't retrigger from our Helm commit below

permissions:
  contents: write   # needed for the Helm commit step

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    name: Install, Lint, Build, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install (CI)
        run: npm ci

      # optional: type-check if you use TS
      - name: Typecheck
        if: hashFiles('tsconfig.json') != ''
        run: npm run typecheck --if-present

      - name: Lint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      # set env if Next build needs secrets (avoid undefined env during build)
      - name: Build
        env:
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }}
          # add any other NEXT_* or NEXT_PUBLIC_* your build reads
        run: npm run build

      - name: Test (CI)
        env:
          NODE_ENV: test
          CI: true
        run: |
          # Jest: prefer --ci; Vitest: use --run
          npm test -- --ci --reporters=default --reporters=jest-junit || npm test -- --run
        continue-on-error: false

  docker_push:
    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/next-js-app:${{ github.run_id }}
            ${{ secrets.DOCKERHUB_USERNAME }}/next-js-app:latest

  update-helm-tag:
    name: Update Helm tag
    runs-on: ubuntu-latest
    needs: docker_push
    steps:
      - name: Checkout (with token)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}  # PAT if you need to bypass branch protection

      - name: Update tag in Helm chart
        run: |
          sudo git config --system --add safe.directory "$(pwd)"
          sed -i 's/tag: .*/tag: "'${{ github.run_id }}'"/' helm/js-app-chart/values.yaml

      - name: Commit and push
        run: |
          git config user.email "ci-bot@users.noreply.github.com"
          git config user.name "ci-bot"
          git add helm/js-app-chart/values.yaml
          git commit -m "ci: bump image tag to ${{ github.run_id }}" || echo "No changes"
          git push
